Update Jenkinsfile

diff --git a/employee-management-app/Jenkinsfile b/employee-management-app/Jenkinsfile
--- a/employee-management-app/Jenkinsfile
+++ b/employee-management-app/Jenkinsfile
@@ -7,9 +7,10 @@ pipeline {
     }
 
     environment {
-        DEPLOY_DIR = 'C:\\deploy'
-        APP_NAME   = 'employee-management-app.jar'
-        APP_PORT   = '8085'
+        DEPLOY_DIR  = 'C:\\deploy'
+        APP_NAME    = 'employee-management-app.jar'
+        APP_PORT    = '8085'
+        BUILD_VER   = "1.0.${BUILD_NUMBER}"
     }
 
     stages {
@@ -18,6 +19,13 @@ pipeline {
             steps {
                 git branch: 'employee-management-app',
                     url: 'https://github.com/bhagwan-raut/master.git'
+            }
+        }
+
+        stage('Set Version') {
+            steps {
+                bat "mvn versions:set -DnewVersion=${BUILD_VER}"
+                echo "Building version: ${BUILD_VER}"
             }
         }
 
@@ -54,18 +62,38 @@ pipeline {
         stage('Start App') {
             steps {
                 bat 'start /B java -jar %DEPLOY_DIR%\\%APP_NAME% > %DEPLOY_DIR%\\app.log 2>&1'
-                echo 'App started at http://localhost:8085'
+                echo "App version ${BUILD_VER} started at http://localhost:8085"
             }
         }
-    }
+
+        stage('Tag Build on GitHub') {
+            steps {
+                bat "git tag -a v${BUILD_VER} -m \"Jenkins Build ${BUILD_VER}\""
+                bat "git push https://YOUR_TOKEN@github.com/bhagwan-raut/master.git v${BUILD_VER}"
+            }
+        }
+
+       stage('Commit Build Number') {
+        steps {
+        sshagent(['github-ssh']) {
+            bat "git config user.email \"bhagwanraut0597@gmail.com\""
+            bat "git config user.name \"bhagwan-raut\""
+            bat "echo ${BUILD_VER} > build-version.txt"
+            bat "git add build-version.txt"
+            bat "git commit -m \"Jenkins Auto Build - Version ${BUILD_VER} [skip ci]\""
+            bat "git push git@github.com:bhagwan-raut/master.git HEAD:employee-management-app"
+                }
+            }
+        }
+     }
 
     post {
         success {
-            echo '🎉 Build and Deploy Successful!'
-            echo 'Access at: http://localhost:8085/api/employees'
+            echo "✅ Build ${BUILD_VER} Successful!"
+            echo "Access at: http://localhost:8085/api/employees"
         }
         failure {
-            echo '❌ Build Failed! Check Console Output.'
+            echo "❌ Build ${BUILD_VER} Failed!"
         }
     }
 }
